# Generated by Django 6.1 on 2026-08-20 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('summary', models.TextField()),
                ('subheadline', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('author', models.CharField(default='THE MP BLAST रिपोर्टर', max_length=150)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/featured/')),
                ('image_caption', models.CharField(blank=True, max_length=300)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_breaking', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='core.category')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_type', models.CharField(choices=[('top_bar', 'Top Breaking Bar'), ('hero', 'Hero'), ('featured', 'Featured')], max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_placements', to='core.article')),
            ],
            options={
                'verbose_name': 'Editorial Placement',
                'verbose_name_plural': 'Editorial Placements',
                'ordering': ['placement_type', 'display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published', '-published_at'], name='core_articl_is_publ_1a9bac_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'is_published', '-published_at'], name='core_articl_categor_8bb27f_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialplacement',
            index=models.Index(fields=['placement_type', 'is_active', 'display_order'], name='core_editor_placeme_634935_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialplacement',
            index=models.Index(fields=['placement_type', 'start_at', 'end_at'], name='core_editor_placeme_5e7a4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='editorialplacement',
            constraint=models.UniqueConstraint(fields=('article', 'placement_type'), name='unique_article_placement_type'),
        ),
    ]
