# Generated by Django 6.1 on 2026-08-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialplacement',
            name='placement_type',
            field=models.CharField(choices=[('breaking_ticker', 'Breaking News Ticker'), ('hero_featured', 'Hero Featured'), ('latest_news', 'Latest News')], max_length=30),
        ),
    ]
