# Generated by Django 6.1 on 2026-08-20 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_editorialplacement_placement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('heading', 'Heading'), ('quote', 'Quote')], max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('heading', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/content/images/')),
                ('image_caption', models.CharField(blank=True, max_length=300)),
                ('image_alt', models.CharField(blank=True, max_length=300)),
                ('video', models.FileField(blank=True, null=True, upload_to='articles/content/videos/')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='articles/content/video-thumbnails/')),
                ('video_title', models.CharField(blank=True, max_length=300)),
                ('video_caption', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='core.article')),
            ],
            options={
                'verbose_name': 'Article Content Block',
                'verbose_name_plural': 'Article Content Blocks',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['article', 'display_order'], name='core_articl_article_cf2f5d_idx')],
            },
        ),
    ]
