# Generated by Django 6.1 on 2026-08-20 15:06

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_articlecontentblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/featured/', validators=[core.validators.validate_article_image]),
        ),
        migrations.AlterField(
            model_name='articlecontentblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/content/images/', validators=[core.validators.validate_article_image]),
        ),
        migrations.AlterField(
            model_name='articlecontentblock',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='articles/content/videos/', validators=[core.validators.validate_article_video]),
        ),
        migrations.AlterField(
            model_name='articlecontentblock',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='articles/content/video-thumbnails/', validators=[core.validators.validate_article_image]),
        ),
    ]
